INSERT INTO JAVA_SCRIPT_FRAMEWORK values (1,CURRENT_TIMESTAMP,'asdasd');
INSERT INTO JAVA_SCRIPT_FRAMEWORK values (2,CURRENT_TIMESTAMP,'fbdfgbdfb');
INSERT INTO JAVA_SCRIPT_FRAMEWORK values (3,CURRENT_TIMESTAMP,'rgesdfsd');

INSERT INTO JAVA_SCRIPT_FRAMEWORK_VERSION values (1,'1111111',1);
INSERT INTO JAVA_SCRIPT_FRAMEWORK_VERSION values (2,'2222222',1);
INSERT INTO JAVA_SCRIPT_FRAMEWORK_VERSION values (3,'3333333',1);
INSERT INTO JAVA_SCRIPT_FRAMEWORK_VERSION values (4,'4444444',2);
INSERT INTO JAVA_SCRIPT_FRAMEWORK_VERSION values (5,'55555555',2);